---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab9-app
  namespace: lab9
  labels:
    app: lab9-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab9-app
  template:
    metadata:
      labels:
        app: lab9-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: app-source
          configMap:
            name: lab9-app-src
      containers:
        - name: lab9-app
          image: localhost:32000/python-ci:lab
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/server.py"]
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-source
              mountPath: /app
          env:
            - name: OPA_URL
              value: "http://opa:8181"
            - name: PORT
              value: "3000"
            - name: APP_NAME
              value: "lab9-app"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }
          securityContext:
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lab9-app
  namespace: lab9
  labels:
    app: lab9-app
spec:
  selector:
    app: lab9-app
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP